# Welcome to Numpy Jupyter

In [1]:
import numpy as np

**int8** 
is used for 8 byte if we exceed it more than 8 byte it will give us an error we can use **int64 int32** also, This is known as memory management

In [2]:
myaray = np.array([3,43,23,5],np.int64)

**[[0,1,2,3,4]]** the two square braket is represent as the 2-D array and if I will use **[0,1,2,3,4]** the one square braket represent as the single 1-D array

In [3]:
myaray[0]


3

In [4]:
myarr = np.array([[3,2,43,21]],np.int64)

In [5]:
myarr[0,1]

2

In [7]:
# How to identify which information of data shape is it

myarr.shape

(1, 4)

In [8]:
# How to identify what is it type of data in it

myarr.dtype

dtype('int64')

In [9]:
myarr[0,3] = 530

In [10]:
myarr

array([[  3,   2,  43, 530]], dtype=int64)

# Introduction

**There are 5 general mechanisms for vreating arrays:**

**1.** Conversion from other Python structures (e.g., lists, tuples)

**2.** Intrinsic numpy array creation objects (e.g., arrange, ones, zeros, etc.)

**3.** Reading arrays from disk, either from standard or custom formats

**4.** Creating arrays from raw bytes through the use of strings or buffers

**5.** Use of special library functions (e.g., random)

In [11]:
# Array creation: Conversion from other Python structures

listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
listarray.dtype

dtype('int32')

In [14]:
listarray.size


9

In [15]:
listarray.shape

(3, 3)

In [16]:
np.array({32,23,23})

array({32, 23}, dtype=object)

**dtype = object** creation isn't efficient to use so we will use most commonly inttype or float type data, because it will disturb you in calculations

# Instrinction function

In [17]:
zeros = np.zeros((2,5))

In [18]:
zeros.size

10

In [19]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
zeros.dtype

dtype('float64')

In [22]:
# Simple increment in number till 0 to 14

rng = np.arange(15)

In [23]:
rng 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
# It will gives the 1 to 5 range linearly exactly equally space in 12 element give us

lspace = np.linspace(1,50,12)

In [27]:
lspace

array([ 1.        ,  5.45454545,  9.90909091, 14.36363636, 18.81818182,
       23.27272727, 27.72727273, 32.18181818, 36.63636364, 41.09090909,
       45.54545455, 50.        ])

In [28]:
# It will gives a empty array and in this element which we get is random

emmp = np.empty((4,6))

In [29]:
emmp


array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.11260280e-306, 4.45061456e-308, 1.69120552e-306],
       [7.56587585e-307, 1.37961302e-306, 1.05699242e-307,
        8.01097889e-307, 1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
        1.33511018e-306, 6.23057689e-307, 9.45754852e-308],
       [1.27946076e-307, 1.05700515e-307, 1.11261774e-306,
        1.29060871e-306, 8.34424766e-308, 2.12203497e-312]])

In [30]:
# it will copy that array and make that array as empty 

emplike = np.empty_like(lspace)

In [31]:
emplike

array([ 1.        ,  5.45454545,  9.90909091, 14.36363636, 18.81818182,
       23.27272727, 27.72727273, 32.18181818, 36.63636364, 41.09090909,
       45.54545455, 50.        ])

In [33]:
# it will create 45 x 45 identity array

# np.eye is also make an 2-D identity array

ide = np.identity(45)

In [34]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [35]:
ide.shape

(45, 45)

In [37]:
arr = np.arange(99)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
#  we must consider on this step the array after multiply x and y axis
# we should get exact axis which we have an actual array
# Like if i will apply (3,31) it will through an error so
# I will use this 3 x 33 = 99 and 3 x 31 = 93

# There are 3 rows and 33 columns

abc = arr.reshape(3, 33)

In [40]:
abc

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [43]:
# ravel() function convert 2-D array into the 1-D Array

abc = abc.ravel()

In [44]:
abc


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [45]:
arr.shape

(99,)

In [46]:
abc.shape

(99,)

In [47]:
# This is the 1Row and 2Column and with fill it with ones

aray = np.ones((1,2))

In [48]:
aray

array([[1., 1.]])

In [49]:
# This is 2 X 2 array and fill with 7

fully =  np.full((2,2),7)

In [50]:
fully

array([[7, 7],
       [7, 7]])

In [52]:
# It will create 2X2 random array

ran = np.random.random((2,2))

In [53]:
ran

array([[0.21397233, 0.72893535],
       [0.5404114 , 0.64579383]])

# Slicing

In [54]:
a=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])

In [72]:
# 1:2 is representing a Rows and 2:4 is representing a ccolumn

b = a[1:2,2:4]

print(b)

[[7 8]]


**How we can use axis=0** 

Actually it's represent the column1 , Column 2, column 3 values.

In [76]:
# This sum the value column wise it's direction is up to down |

a.sum(axis = 0)

array([15, 18, 21, 24])


**How we can use axis=1**

Actually it's represent the Row1 , Row 2, Row 3 values.

In [77]:
# This sum the value row wise it's direction is left to right |

a.sum(axis = 1)

array([10, 26, 42])

# How to Transpose an Array

In [78]:
# Capital T is transpose the array

a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# How to contain an items of an array through flat

In [79]:
a.flat

In [80]:
#Such as

for item in a.flat:
    print(item)

1
2
3
4
5
6
7
8
9
10
11
12


# How to check dimension


In [81]:
a.ndim

2

In [82]:
a.size

12

In [84]:
# how many space containn through the array by your elements

a.nbytes

48

In [104]:
one = np.array([1,3,4,634,2])
two = np.array([1,3,214,26,2])

In [105]:
# It gives us the index number where's our maximum element exists

one.argmax()
two.argmax()

2

In [107]:
# It gives us the index number where's our minimum element exists

one.argmin()

0

In [108]:
# It's give us those indexes which sort the array

one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [109]:
a.argmin()

0

In [110]:
a.argmax(axis=0)

array([2, 2, 2, 2], dtype=int64)

In [111]:
a.argmax(axis=1)

array([3, 3, 3], dtype=int64)

In [115]:
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [118]:
# It's change the indexes rows and column wise

a.reshape((12,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

# Mathematical Operation

In [121]:
ab = np.array([[2,3,4,3],
               [1,1,5,5],
               [3,6,7,6]])

In [122]:
a +ab

array([[ 3,  5,  7,  7],
       [ 6,  7, 12, 13],
       [12, 16, 18, 18]])

In [124]:
# Extend the list

[21,33]+[12,12]

[21, 33, 12, 12]

In [125]:
a * ab

array([[ 2,  6, 12, 12],
       [ 5,  6, 35, 40],
       [27, 60, 77, 72]])

In [127]:
# It's taking an square root of the element

np.sqrt(ab)

array([[1.41421356, 1.73205081, 2.        , 1.73205081],
       [1.        , 1.        , 2.23606798, 2.23606798],
       [1.73205081, 2.44948974, 2.64575131, 2.44948974]])

In [129]:
# Sum of all ellements

ab.sum()

46

In [130]:
ab.max()

7

In [131]:
ab.min()

1

# How to find the Element

In [132]:
np.where(ab>5)

(array([2, 2, 2], dtype=int64), array([1, 2, 3], dtype=int64))

**(array([2, 2, 2], dtype=int64), array([1, 2, 3], dtype=int64))**


Here is first array[2] **Row** to second array[1] **Column**

Here is first array[2] **Row** to second array[2] **Column**

Here is first array[2] **Row** to second array[3] **Column**

In [133]:
type(np.where(ab>5))

tuple

In [134]:
# It will count the non zero elements

np.count_nonzero(ab)

12

In [135]:
# Now it's tell us where is non zero element presents

np.nonzero(ab)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

# Check the size of array

In [136]:
import sys

In [137]:
check = [0,4,55,2]

In [138]:
nparr = np.array(check)

In [139]:
# Size of simple array bytes

sys.getsizeof(1) * len(check)

112

In [141]:
# Size of numpy array in bytes

nparr.itemsize * nparr.size

16

In [ ]:
# https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.ndarray.html